# For help please refer to https://dev.bukkit.org/projects/passwordprotect
hash: SHA-512
opsRequirePassword: true
disableJailArea: false
cleanPassword: false
password: ''
passwordClean: ''
prevent:
  movement: true
  interaction: true
  interactionMobs: true
  itemPickup: true
  itemDrop: true
  portal: true
  blockPlace: true
  blockBreak: true
  triggering: true
  attacks: true
  damage: true
  chat: true
  deathDrops: true
  flying: true
wrongAttempts:
  kick: 3
  ban: 5
  banIP: true
broadcast:
  kick: true
  ban: true
darkness: true
slowness: true
allowedCommands:
- help
- rules
- motd
teleportBack: true
loginMessage: true
